// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Context;

namespace Repositories.Migrations
{
    [DbContext(typeof(FoodTownDbContext))]
    [Migration("20201225144027_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExactAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsItActive")
                        .HasColumnType("bit");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AppUserRoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("AppUserRoleId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Entities.AppUserRole", b =>
                {
                    b.Property<int>("AppUserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppUserRoleId");

                    b.ToTable("AppUserRole");
                });

            modelBuilder.Entity("Entities.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CreditCardId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Iva")
                        .HasColumnType("float");

                    b.Property<double>("SubTotal")
                        .HasColumnType("float");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("BillId");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("Entities.BillItem", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<double>("Iva")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("SubTotal")
                        .HasColumnType("float");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("BillId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("BillItem");
                });

            modelBuilder.Entity("Entities.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Brand");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            CategoryId = 1,
                            Name = "The Fruit Company"
                        },
                        new
                        {
                            BrandId = 2,
                            CategoryId = 1,
                            Name = "Harry & David"
                        },
                        new
                        {
                            BrandId = 3,
                            CategoryId = 1,
                            Name = "A Gift Inside"
                        },
                        new
                        {
                            BrandId = 4,
                            CategoryId = 2,
                            Name = "Tyson Foods"
                        },
                        new
                        {
                            BrandId = 5,
                            CategoryId = 2,
                            Name = "JBS S.A"
                        },
                        new
                        {
                            BrandId = 6,
                            CategoryId = 2,
                            Name = "Cargill"
                        },
                        new
                        {
                            BrandId = 7,
                            CategoryId = 3,
                            Name = "SeaPak Shrimp & Seafood"
                        },
                        new
                        {
                            BrandId = 8,
                            CategoryId = 3,
                            Name = "markfoods"
                        },
                        new
                        {
                            BrandId = 9,
                            CategoryId = 3,
                            Name = "Inland Seafood"
                        },
                        new
                        {
                            BrandId = 10,
                            CategoryId = 4,
                            Name = "Nestle"
                        },
                        new
                        {
                            BrandId = 11,
                            CategoryId = 4,
                            Name = "Danone"
                        },
                        new
                        {
                            BrandId = 12,
                            CategoryId = 4,
                            Name = "Lactalis"
                        },
                        new
                        {
                            BrandId = 13,
                            CategoryId = 5,
                            Name = "Lundberg Family Farms"
                        },
                        new
                        {
                            BrandId = 14,
                            CategoryId = 5,
                            Name = "Grain Miller"
                        },
                        new
                        {
                            BrandId = 16,
                            CategoryId = 6,
                            Name = "Plant Therapy"
                        });
                });

            modelBuilder.Entity("Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Fruits & Vegetables"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Meat"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Sea Food"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Dairy"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Grains"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Oils"
                        });
                });

            modelBuilder.Entity("Entities.CreditCard", b =>
                {
                    b.Property<int>("CreditCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CVV")
                        .HasColumnType("int")
                        .HasMaxLength(3);

                    b.Property<string>("CreditCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOnCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CreditCardId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CreditCard");
                });

            modelBuilder.Entity("Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsItActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ItemId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "They may have derived from Japan, but our Imperial Fuji Apples are 100% direct from our Pacific Northwest orchards! Their pretty pinkish flush over a yellow-green background with a crisp, juicy and refreshingly sweet flavor make these apples one of our customer-favorites! ",
                            ImageName = "Red Apple(Fruit Company)_e92a8662-259f-4244-af3f-47db7b1dc34f",
                            IsItActive = true,
                            Name = "Red Apple",
                            Price = 1.0
                        },
                        new
                        {
                            ItemId = 2,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Bring the sunshine to your front door with these supremely sweet Valencia Oranges. Known as the ",
                            ImageName = "Red Apple(Fruit Company)_e92a8662-259f-4244-af3f-47db7b1dc34f.jpeg",
                            IsItActive = true,
                            Name = "Orange",
                            Price = 0.5
                        },
                        new
                        {
                            ItemId = 3,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Get ready - we're about to reveal one of the best-kept secrets of pear-lovers. Our Forelle Mini Pears are extremely sugary, very juicy, and available only from October through late winter. With their bell-shaped body and attractive crimson freckling, a bowl of ripening Forelles makes a stunning edible centerpiece during the holidays and a perfect hostess gift for winter parties. ",
                            ImageName = "Pear(Fruit Company)_9b4ac9f9-c2ad-4455-8a53-556fbe9846ac.jpeg",
                            IsItActive = true,
                            Name = "Pear",
                            Price = 0.75
                        },
                        new
                        {
                            ItemId = 4,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "Can you just hear the crash of the ocean waves and feel the golden rays on your face? Our sun-ripened pineapples bring a taste of abundant juices and sweet mouth-tingling taste. So go ahead...invite your closest friends over for a tropical-themed party, with this pineapple as your centerpiece. ",
                            ImageName = "Pineapple(Harry & David)_c378bd7f-248b-4f11-8caa-064c05f7e713.jpeg",
                            IsItActive = true,
                            Name = "Pineapple",
                            Price = 0.5
                        },
                        new
                        {
                            ItemId = 5,
                            BrandId = 3,
                            CategoryId = 1,
                            Description = "Send fresh blueberries grown in our own Blueberry Fields in the foothills of beautiful Mount Hood. When harvest begins our blueberries will be picked the same day we ship them to you or your recipient to ensure the freshest berries available. Our expert gift designers will make sure your blueberries arrive delicious and gift-ready!",
                            ImageName = "Blueberries(A Gift Inside)_50ff5c6d-7fab-42c6-b333-318df8605b91.jpeg",
                            IsItActive = true,
                            Name = "Blueberries",
                            Price = 1.25
                        },
                        new
                        {
                            ItemId = 6,
                            BrandId = 4,
                            CategoryId = 2,
                            Description = "How did ancient civilizations fuel themselves to build pyramids or win sword battles? Meat. If it worked for them, Jack Link’s beef jerky can definitely help you power through a late day at work, tackle your honey-do list or fuel a workout. ",
                            ImageName = "Beef(Tyson Foods)_21c4f102-5f81-4abb-b590-37230b154460.jpeg",
                            IsItActive = true,
                            Name = "Beef",
                            Price = 20.0
                        },
                        new
                        {
                            ItemId = 7,
                            BrandId = 5,
                            CategoryId = 2,
                            Description = "Handmade Salami - Creminelli meats are handmade under the supervision of master artisan, Cristiano Creminelli. Cristiano insists on using choice cuts of meat from select breeds, fed with organic white grains, and raised on small family farms. ",
                            ImageName = "Salami(JBS)_fee93094-c322-4d77-918a-b6ebd495235d.jpeg",
                            IsItActive = true,
                            Name = "Salami Genoa Charcuterie",
                            Price = 17.530000000000001
                        },
                        new
                        {
                            ItemId = 8,
                            BrandId = 6,
                            CategoryId = 2,
                            Description = "Pat LaFrieda's Boneless Chicken Thighs come from chickens raised on small, free range farms in Lancaster, Pennsylvania. Raised without antibiotics, these tender dark meat thighs are great for any time of year. ",
                            ImageName = "Chicken(Cargill)_49297c08-8677-4ae2-b097-48e74d59a26d.jpeg",
                            IsItActive = true,
                            Name = "Chicken Breast",
                            Price = 23.989999999999998
                        },
                        new
                        {
                            ItemId = 9,
                            BrandId = 6,
                            CategoryId = 2,
                            Description = "Fresh Fields, Turkey Breast Peppered Charcuterie ",
                            ImageName = "Turkey(Cargill)_ae50ca7d-2b21-45e0-8fa4-401baa612ab0.jpeg",
                            IsItActive = true,
                            Name = "Turkey Breast Peppered Charcuterie",
                            Price = 13.289999999999999
                        },
                        new
                        {
                            ItemId = 10,
                            BrandId = 6,
                            CategoryId = 2,
                            Description = "You only get one shot at living a great life. Better make it a good one! The best Items are made from the best ingredients. We carefully source all of our materials from farmers who share our belief that it’s worth the time, work, and effort to make things great. ",
                            ImageName = "Ham(Cargill)_1cdd109f-7902-441d-8ab2-1ca75fb5bfd4.jpeg",
                            IsItActive = true,
                            Name = "Ham",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            ItemId = 11,
                            BrandId = 7,
                            CategoryId = 4,
                            Description = "Our seafood is traceable to farm or fishery, and we work hard to source it only from responsibly managed farms and sustainable wild fisheries.  ",
                            ImageName = "Shrimp(SeaPak Shrimp & Seafood)_19a33b26-730f-459f-ba54-0cb085468cc2.jpeg",
                            IsItActive = true,
                            Name = "Shrimp",
                            Price = 1.99
                        },
                        new
                        {
                            ItemId = 12,
                            BrandId = 8,
                            CategoryId = 4,
                            Description = "In the Whole Foods Market Seafood department, our rigorous standards help maintain healthy fish populations, protect ecosystems and build a more sustainable seafood supply for everyone. From sustainable wild-caught salmon to Responsibly Farmed shrimp, we do seafood better — and we mean it. ",
                            ImageName = "Salmon(markfoods)_bbb5af69-69e6-4c7c-b5f1-819a8b350235.jpeg",
                            IsItActive = true,
                            Name = "Salmon",
                            Price = 5.9900000000000002
                        },
                        new
                        {
                            ItemId = 13,
                            BrandId = 9,
                            CategoryId = 4,
                            Description = "Whether you’re squeezing in lunch between meetings during a busy workday or want a quick, protein-packed snack between soccer practice, school and other daily errands, StarKist Chunk Light Tuna in Water is the perfect choice! Each of our 5 oz. tuna cans features wild caught tuna with a naturally mild flavor people have come to expect from StarKist Plus, it’s soy and gluten free and works well with Keto, Paleo, Whole30, Mediterranean and Weight Watchers diet plans! This packaged tuna is an excellent, natural source of protein and Omega 3s , and it has 20g of protein and 90 calories per can. Plus, it’s a great, quick and easy way to add seafood to your diet! Tuna is naturally lower in fat so it’s a wholesome way to add variety to your meals. Easy to store, you can stock up with this 48-Pack of tuna cans, and keep these tuna singles in your office, pantry at home and even in your diaper bag or car! An industry innovator, StarKist was the first brand to introduce StarKist single-serve pouch Items, which include Tuna, Salmon and Chicken Creations, and StarKist Selects E.V.O.O. As America’s favorite tuna*, StarKist represents a tradition of quality, consumer trust and a commitment to sustainability. ",
                            ImageName = "Tuna(Inland Seafood)_bbb5af69-69e6-4c7c-b5f1-819a8b350235.jpeg",
                            IsItActive = true,
                            Name = "Tuna",
                            Price = 4.7199999999999998
                        },
                        new
                        {
                            ItemId = 14,
                            BrandId = 10,
                            CategoryId = 4,
                            Description = "Our seafood is traceable to farm or fishery, and we work hard to source it only from responsibly managed farms and sustainable wild fisheries. ",
                            ImageName = "Milk(Nestle)_19a33b26-730f-459f-ba54-0cb085468cc2.jpeg",
                            IsItActive = true,
                            Name = "Milk",
                            Price = 2.9900000000000002
                        },
                        new
                        {
                            ItemId = 15,
                            BrandId = 11,
                            CategoryId = 4,
                            Description = "All cheeses from the Whole Foods Market Cheese department are exclusively selected and passionately sourced from farmers and producers around the world",
                            ImageName = "Cheese(Danone)_bbb5af69-69e6-4c7c-b5f1-819a8b350235.jpeg",
                            IsItActive = true,
                            Name = "Cheese",
                            Price = 1.5
                        },
                        new
                        {
                            ItemId = 16,
                            BrandId = 11,
                            CategoryId = 4,
                            Description = "Our yogurts are made from real yogurt and absolutely no preservatives! We collect fresh milk from an exclusive network of farms and cows. The milk is pasteurized and cultures are added, transforming the milk into yogurt. Then the yogurt is cooled and real delicious fruit is added. Finally, the pouches are filled, sealed, and heat treated, so they’re shelf-stable. ",
                            ImageName = "Yogurt(Danone)_070d168a-e7c6-439a-a847-8e09ea070a0f.jpeg",
                            IsItActive = true,
                            Name = "Yogurt",
                            Price = 2.9900000000000002
                        },
                        new
                        {
                            ItemId = 17,
                            BrandId = 12,
                            CategoryId = 4,
                            Description = "Our Ghee is made the old fashion way with nothing added to it, using only AA unsalted butter sourced from Wisconsin. Amber & Gold Ghee is a Go Texan certified Item because it is handmade in Magnolia, TX. Authenthic Ghee is scientifically proven to be the healthiest fat for the human body. It can replace any cooking oil or fat in the kitchen. ",
                            ImageName = "Butter(Lactalis)_fd713ee4-bdce-446d-87b0-6881e1b8f3e9.jpeg",
                            IsItActive = true,
                            Name = "Butter",
                            Price = 1.99
                        },
                        new
                        {
                            ItemId = 18,
                            BrandId = 13,
                            CategoryId = 5,
                            Description = "Nature's Earthly Choice Cauliflower Rice",
                            ImageName = "Rice(Lundberg Family Farms)_070d168a-e7c6-439a-a847-8e09ea070a0f.jpeg",
                            IsItActive = true,
                            Name = "Rice",
                            Price = 3.9900000000000002
                        },
                        new
                        {
                            ItemId = 19,
                            BrandId = 14,
                            CategoryId = 5,
                            Description = "A favorite among black bean connoisseurs. Faraon Black Beans are carefully selected from the best crops available, consistently offering a true black bean color and authentic taste. When cooked, Faraon is sure to please with a wonderfully thick and delicious bean broth. Faraon brand is demanded by the most knowledgeable consumers. Enjoy!",
                            ImageName = "Beans(Grain Miller)_fd713ee4-bdce-446d-87b0-6881e1b8f3e9.jpeg",
                            IsItActive = true,
                            Name = "Beans",
                            Price = 2.9900000000000002
                        },
                        new
                        {
                            ItemId = 20,
                            BrandId = 14,
                            CategoryId = 5,
                            Description = "Canola Oil is light flavored, and great for cooking and frying",
                            ImageName = "Canola Oil(Plant Therapy)_fd713ee4-bdce-446d-87b0-6881e1b8f3e9.jpeg",
                            IsItActive = true,
                            Name = "Canola Oil",
                            Price = 6.9900000000000002
                        });
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CreditCardId")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.HasIndex("AddressId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("CreditCardId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<double>("Iva")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("SubTotal")
                        .HasColumnType("float");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("OrderId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Entities.Address", b =>
                {
                    b.HasOne("Entities.AppUser", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.AppUser", b =>
                {
                    b.HasOne("Entities.AppUserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("AppUserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Bill", b =>
                {
                    b.HasOne("Entities.Address", "DeliveryAddress")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.AppUser", "Customer")
                        .WithMany("Bills")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.BillItem", b =>
                {
                    b.HasOne("Entities.Item", "Item")
                        .WithMany("Bills")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Brand", b =>
                {
                    b.HasOne("Entities.Category", "Category")
                        .WithMany("Brands")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.CreditCard", b =>
                {
                    b.HasOne("Entities.AppUser", "Customer")
                        .WithMany("CreditCards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Item", b =>
                {
                    b.HasOne("Entities.Brand", "Brand")
                        .WithMany("Items")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Order", b =>
                {
                    b.HasOne("Entities.Address", null)
                        .WithMany("Orders")
                        .HasForeignKey("AddressId");

                    b.HasOne("Entities.AppUser", "Client")
                        .WithOne("Order")
                        .HasForeignKey("Entities.Order", "ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.CreditCard", null)
                        .WithMany("Orders")
                        .HasForeignKey("CreditCardId");
                });

            modelBuilder.Entity("Entities.OrderItem", b =>
                {
                    b.HasOne("Entities.Item", "Item")
                        .WithMany("Orders")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
