// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Context;

namespace Repositories.Migrations
{
    [DbContext(typeof(RealStateDbContext))]
    [Migration("20210310220715_smallImprovements")]
    partial class smallImprovements
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Entities.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Iva")
                        .HasColumnType("float");

                    b.Property<int>("Months")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("SubTotal")
                        .HasColumnType("float");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("BillId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("HouseId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("Entities.BillService", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("BillId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BillService");
                });

            modelBuilder.Entity("Entities.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeatureId");

                    b.ToTable("Feature");

                    b.HasData(
                        new
                        {
                            FeatureId = 1,
                            Name = "Garage"
                        },
                        new
                        {
                            FeatureId = 2,
                            Name = "Yard"
                        },
                        new
                        {
                            FeatureId = 3,
                            Name = "Garden"
                        },
                        new
                        {
                            FeatureId = 4,
                            Name = "Swimming Pool"
                        },
                        new
                        {
                            FeatureId = 5,
                            Name = "Terrace"
                        },
                        new
                        {
                            FeatureId = 6,
                            Name = "Two or more floors"
                        });
                });

            modelBuilder.Entity("Entities.House", b =>
                {
                    b.Property<int>("HouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsItAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.HasKey("HouseId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("House");

                    b.HasData(
                        new
                        {
                            HouseId = 1,
                            Bathrooms = 1,
                            Bedrooms = 1,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            ImageName = "House1.jpeg",
                            IsItAvailable = true,
                            Name = "House #1",
                            Price = 100000.0,
                            ProvinceId = 1,
                            Size = 100.0
                        },
                        new
                        {
                            HouseId = 2,
                            Bathrooms = 2,
                            Bedrooms = 2,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            ImageName = "House2.jpeg",
                            IsItAvailable = true,
                            Name = "House #2",
                            Price = 125000.0,
                            ProvinceId = 2,
                            Size = 300.0
                        },
                        new
                        {
                            HouseId = 3,
                            Bathrooms = 1,
                            Bedrooms = 2,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            ImageName = "House3.jpeg",
                            IsItAvailable = true,
                            Name = "House #3",
                            Price = 155000.0,
                            ProvinceId = 3,
                            Size = 180.0
                        },
                        new
                        {
                            HouseId = 4,
                            Bathrooms = 2,
                            Bedrooms = 4,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            ImageName = "House4.jpeg",
                            IsItAvailable = true,
                            Name = "House #4",
                            Price = 250000.0,
                            ProvinceId = 4,
                            Size = 225.0
                        },
                        new
                        {
                            HouseId = 5,
                            Bathrooms = 3,
                            Bedrooms = 3,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            ImageName = "House5.jpeg",
                            IsItAvailable = true,
                            Name = "House #5",
                            Price = 330000.0,
                            ProvinceId = 5,
                            Size = 500.0
                        },
                        new
                        {
                            HouseId = 6,
                            Bathrooms = 3,
                            Bedrooms = 2,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            ImageName = "House6.jpeg",
                            IsItAvailable = true,
                            Name = "House #6",
                            Price = 210000.0,
                            ProvinceId = 6,
                            Size = 190.0
                        },
                        new
                        {
                            HouseId = 7,
                            Bathrooms = 2,
                            Bedrooms = 4,
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            ImageName = "House7.jpeg",
                            IsItAvailable = true,
                            Name = "House #7",
                            Price = 300000.0,
                            ProvinceId = 7,
                            Size = 260.0
                        });
                });

            modelBuilder.Entity("Entities.HouseFeature", b =>
                {
                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.HasKey("HouseId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("HouseFeature");

                    b.HasData(
                        new
                        {
                            HouseId = 1,
                            FeatureId = 1
                        },
                        new
                        {
                            HouseId = 1,
                            FeatureId = 2
                        },
                        new
                        {
                            HouseId = 1,
                            FeatureId = 3
                        },
                        new
                        {
                            HouseId = 2,
                            FeatureId = 2
                        },
                        new
                        {
                            HouseId = 3,
                            FeatureId = 2
                        },
                        new
                        {
                            HouseId = 3,
                            FeatureId = 3
                        },
                        new
                        {
                            HouseId = 4,
                            FeatureId = 2
                        },
                        new
                        {
                            HouseId = 4,
                            FeatureId = 3
                        },
                        new
                        {
                            HouseId = 4,
                            FeatureId = 6
                        },
                        new
                        {
                            HouseId = 5,
                            FeatureId = 1
                        },
                        new
                        {
                            HouseId = 5,
                            FeatureId = 2
                        },
                        new
                        {
                            HouseId = 5,
                            FeatureId = 3
                        },
                        new
                        {
                            HouseId = 5,
                            FeatureId = 4
                        },
                        new
                        {
                            HouseId = 5,
                            FeatureId = 5
                        },
                        new
                        {
                            HouseId = 5,
                            FeatureId = 6
                        },
                        new
                        {
                            HouseId = 6,
                            FeatureId = 1
                        },
                        new
                        {
                            HouseId = 6,
                            FeatureId = 2
                        },
                        new
                        {
                            HouseId = 6,
                            FeatureId = 3
                        },
                        new
                        {
                            HouseId = 6,
                            FeatureId = 4
                        },
                        new
                        {
                            HouseId = 6,
                            FeatureId = 5
                        },
                        new
                        {
                            HouseId = 6,
                            FeatureId = 6
                        },
                        new
                        {
                            HouseId = 7,
                            FeatureId = 1
                        },
                        new
                        {
                            HouseId = 7,
                            FeatureId = 2
                        },
                        new
                        {
                            HouseId = 7,
                            FeatureId = 3
                        },
                        new
                        {
                            HouseId = 7,
                            FeatureId = 4
                        },
                        new
                        {
                            HouseId = 7,
                            FeatureId = 5
                        },
                        new
                        {
                            HouseId = 7,
                            FeatureId = 6
                        });
                });

            modelBuilder.Entity("Entities.HouseService", b =>
                {
                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("HouseId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("HouseService");

                    b.HasData(
                        new
                        {
                            HouseId = 1,
                            ServiceId = 3
                        },
                        new
                        {
                            HouseId = 2,
                            ServiceId = 4
                        },
                        new
                        {
                            HouseId = 3,
                            ServiceId = 1
                        },
                        new
                        {
                            HouseId = 3,
                            ServiceId = 2
                        },
                        new
                        {
                            HouseId = 3,
                            ServiceId = 3
                        },
                        new
                        {
                            HouseId = 4,
                            ServiceId = 1
                        },
                        new
                        {
                            HouseId = 4,
                            ServiceId = 2
                        },
                        new
                        {
                            HouseId = 4,
                            ServiceId = 3
                        },
                        new
                        {
                            HouseId = 4,
                            ServiceId = 4
                        },
                        new
                        {
                            HouseId = 5,
                            ServiceId = 1
                        },
                        new
                        {
                            HouseId = 5,
                            ServiceId = 2
                        },
                        new
                        {
                            HouseId = 5,
                            ServiceId = 3
                        },
                        new
                        {
                            HouseId = 5,
                            ServiceId = 4
                        },
                        new
                        {
                            HouseId = 5,
                            ServiceId = 5
                        },
                        new
                        {
                            HouseId = 6,
                            ServiceId = 1
                        },
                        new
                        {
                            HouseId = 6,
                            ServiceId = 2
                        },
                        new
                        {
                            HouseId = 6,
                            ServiceId = 3
                        },
                        new
                        {
                            HouseId = 6,
                            ServiceId = 4
                        },
                        new
                        {
                            HouseId = 6,
                            ServiceId = 5
                        },
                        new
                        {
                            HouseId = 7,
                            ServiceId = 1
                        },
                        new
                        {
                            HouseId = 7,
                            ServiceId = 2
                        },
                        new
                        {
                            HouseId = 7,
                            ServiceId = 3
                        },
                        new
                        {
                            HouseId = 7,
                            ServiceId = 4
                        },
                        new
                        {
                            HouseId = 7,
                            ServiceId = 5
                        });
                });

            modelBuilder.Entity("Entities.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("PaymentMethod");
                });

            modelBuilder.Entity("Entities.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.ToTable("Province");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            Name = "San Jose"
                        },
                        new
                        {
                            ProvinceId = 2,
                            Name = "Alajuela"
                        },
                        new
                        {
                            ProvinceId = 3,
                            Name = "Heredia"
                        },
                        new
                        {
                            ProvinceId = 4,
                            Name = "Cartago"
                        },
                        new
                        {
                            ProvinceId = 5,
                            Name = "Guanacaste"
                        },
                        new
                        {
                            ProvinceId = 6,
                            Name = "Limon"
                        },
                        new
                        {
                            ProvinceId = 7,
                            Name = "Puntarenas"
                        });
                });

            modelBuilder.Entity("Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ServiceId");

                    b.ToTable("Service");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            Description = "lorem ipsum",
                            Name = "Surveillance 24/7",
                            Price = 30000.0
                        },
                        new
                        {
                            ServiceId = 2,
                            Description = "lorem ipsum",
                            Name = "Swimming Pool Maintenance",
                            Price = 13000.0
                        },
                        new
                        {
                            ServiceId = 3,
                            Description = "lorem ipsum",
                            Name = "Garden",
                            Price = 25000.0
                        },
                        new
                        {
                            ServiceId = 4,
                            Description = "lorem ipsum",
                            Name = "House Insurance",
                            Price = 30000.0
                        },
                        new
                        {
                            ServiceId = 5,
                            Description = "lorem ipsum",
                            Name = "Solar Panels",
                            Price = 9000.0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Entities.Bill", b =>
                {
                    b.HasOne("Entities.AppUser", "Customer")
                        .WithMany("Bills")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.House", "House")
                        .WithMany()
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Bills")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.BillService", b =>
                {
                    b.HasOne("Entities.Service", "Service")
                        .WithMany("Bills")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Bill", "Bill")
                        .WithMany("Services")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.House", b =>
                {
                    b.HasOne("Entities.Province", "Province")
                        .WithMany("Houses")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.HouseFeature", b =>
                {
                    b.HasOne("Entities.Feature", "Feature")
                        .WithMany("Houses")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.House", "House")
                        .WithMany("Features")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.HouseService", b =>
                {
                    b.HasOne("Entities.House", "House")
                        .WithMany("Services")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Service", "Service")
                        .WithMany("Houses")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
